language: go

go:
  - 1.3

install:
  - go get -t -v ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - curl https://github.com/coreos/etcd/releases/download/v0.4.6/etcd-v0.4.6-linux-amd64.tar.gz | tar zxf - -C $HOME/gopath/bin
  - go get github.com/apcera/gnatsd

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ginkgo -r -failOnPending -randomizeAllSpecs -race
